"""Classical calorically-perfect-gas oblique-shock relations for a single
attached shock generated by a 2-D compression ramp (weak or strong
branch).

Conventions (radians internally; see DESIGN.md for the full audit):

    M_1   = upstream Mach number (M_1 > 1)
    theta = flow-deflection / compression-ramp angle (0 < theta < theta_max)
    beta  = shock angle, measured from the upstream flow direction
    mu    = Mach angle = asin(1/M_1)

For an attached compression shock: mu < beta < pi/2.

This module implements ONLY a single ramp / single attached oblique
shock. It is not a multi-ramp inlet model and not a shock-train model
(see README.md / DESIGN.md for the Milestone 2 scope boundary).

Fundamental distinction maintained throughout (as in normal_shock.py):

    STATIC PRESSURE RISE:         p2/p1 > 1   (flow compresses)
    STAGNATION-PRESSURE RECOVERY: p0,2/p0,1 < 1  (irreversible entropy rise)

p2/p1 is never referred to as "pressure recovery" anywhere in this project.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import numpy.typing as npt
from scipy.optimize import brentq, minimize_scalar

from scramjet_inlet.gas_dynamics import DEFAULT_GAMMA
from scramjet_inlet.normal_shock import normal_shock

ArrayLike = npt.ArrayLike

# Small numerical offsets used to keep bracketed solves strictly inside the
# open, physically admissible beta domain (mu, pi/2) and away from the
# theta_max stationary point, where the weak/strong brackets would
# otherwise degenerate to a zero-width interval.
_BETA_EPS = 1e-9
_THETA_MAX_EPS = 1e-9


def _validate_M1(M1: ArrayLike) -> np.ndarray:
    M1_arr = np.asarray(M1, dtype=float)
    if np.any(M1_arr <= 1.0):
        raise ValueError(
            f"Oblique-shock relations require M1 > 1 (supersonic upstream flow); got M1={M1}"
        )
    return M1_arr


def _validate_gamma(gamma: ArrayLike) -> np.ndarray:
    gamma_arr = np.asarray(gamma, dtype=float)
    if np.any(gamma_arr <= 1.0):
        raise ValueError(f"gamma must be > 1; got {gamma}")
    return gamma_arr


def mach_angle(M1: ArrayLike) -> np.ndarray:
    """Mach angle mu = asin(1/M1), in radians.

    Requires M1 > 1 (mu is undefined/degenerate for M1 <= 1).
    """
    M1_arr = _validate_M1(M1)
    return np.arcsin(1.0 / M1_arr)


def theta_from_beta(M1: float, beta: float, gamma: float = DEFAULT_GAMMA) -> float:
    """Deflection angle theta (radians) produced by shock angle beta (radians)
    for upstream Mach M1, via the classical theta-beta-M relation:

        tan(theta) = 2*cot(beta) * (M1^2*sin^2(beta) - 1)
                                    / (M1^2*(gamma + cos(2*beta)) + 2)

    Scalar-only (used internally by the bracketed root/optimization solvers
    and exposed for independent testing / figure generation). beta must lie
    in (0, pi/2]; no additional validation is performed here since this is
    an internal building block evaluated only at solver-controlled points.

    Source: classical closed-form theta-beta-M relation (Anderson, Modern
    Compressible Flow); cross-checked against the algebraically equivalent
    form on the NASA Glenn Research Center oblique-shock reference page.
    See DESIGN.md for the full audit.
    """
    M1sq = M1 * M1
    sin_b = np.sin(beta)
    cos_b = np.cos(beta)
    numerator = M1sq * sin_b * sin_b - 1.0
    denominator = M1sq * (gamma + np.cos(2.0 * beta)) + 2.0
    cot_b = cos_b / sin_b
    tan_theta = 2.0 * cot_b * numerator / denominator
    return float(np.arctan(tan_theta))


@dataclass
class DetachmentLimit:
    """Maximum attached-shock deflection angle and the shock angle at which
    it occurs, for a given M1, gamma."""

    M1: float
    theta_max: float  # radians
    beta_at_theta_max: float  # radians


def detachment_limit(M1: float, gamma: float = DEFAULT_GAMMA) -> DetachmentLimit:
    """Compute theta_max(M1, gamma) and the shock angle at which it occurs.

    theta(beta) rises monotonically from 0 at beta=mu to a single interior
    maximum theta_max at some beta*, then falls monotonically back to 0 at
    beta=pi/2 (the normal-shock, zero-deflection limit). This unimodal
    structure is exploited via SciPy's bounded (Brent-derivative) scalar
    minimizer over the bracket (mu, pi/2), which is a robust bracketed
    method appropriate for a smooth unimodal objective -- no unconstrained
    Newton iteration is used anywhere in this module.
    """
    M1_arr = _validate_M1(M1)
    if M1_arr.shape != ():
        raise ValueError("detachment_limit expects a scalar M1")
    gamma_val = float(_validate_gamma(gamma))
    M1_val = float(M1_arr)

    mu = float(mach_angle(M1_val))
    lo = mu + _BETA_EPS
    hi = np.pi / 2.0 - _BETA_EPS

    result = minimize_scalar(
        lambda b: -theta_from_beta(M1_val, b, gamma_val),
        bounds=(lo, hi),
        method="bounded",
        options={"xatol": 1e-14},
    )
    if not result.success:
        raise RuntimeError(
            f"theta_max optimization failed to converge for M1={M1_val}, gamma={gamma_val}: "
            f"{result.message}"
        )
    beta_star = float(result.x)
    theta_star = theta_from_beta(M1_val, beta_star, gamma_val)
    return DetachmentLimit(M1=M1_val, theta_max=theta_star, beta_at_theta_max=beta_star)


def shock_angle(
    M1: float,
    theta: float,
    gamma: float = DEFAULT_GAMMA,
    branch: str = "weak",
) -> float:
    """Solve the theta-beta-M relation for the shock angle beta (radians)
    on the requested branch, for a single attached oblique shock.

    Requires M1 > 1 and 0 < theta <= theta_max(M1, gamma); raises
    ValueError for a detached (theta > theta_max) or degenerate
    (theta <= 0) deflection.

    Branch selection is via explicit interval bracketing -- never an
    unconstrained/arbitrarily-seeded Newton iteration:

        weak branch:   beta in (mu, beta_at_theta_max]
        strong branch: beta in [beta_at_theta_max, pi/2)

    theta(beta) is monotonically increasing on the weak interval and
    monotonically decreasing on the strong interval (see
    `detachment_limit`), so `scipy.optimize.brentq` (a robust bracketed
    root finder) has a guaranteed sign change on each interval and cannot
    silently return a root from the wrong branch.
    """
    M1_val = float(_validate_M1(M1))
    gamma_val = float(_validate_gamma(gamma))
    if not (theta > 0.0):
        raise ValueError(f"theta must be > 0 rad for a compression shock; got theta={theta}")
    if branch not in ("weak", "strong"):
        raise ValueError(f"branch must be 'weak' or 'strong'; got {branch!r}")

    limit = detachment_limit(M1_val, gamma_val)
    if theta > limit.theta_max + 1e-10:
        raise ValueError(
            f"theta={np.degrees(theta):.4f} deg exceeds theta_max="
            f"{np.degrees(limit.theta_max):.4f} deg at M1={M1_val}: shock is DETACHED, "
            "no attached oblique-shock solution exists."
        )

    mu = float(mach_angle(M1_val))

    # theta and theta_max coincide (branches merge) within solver tolerance.
    if abs(theta - limit.theta_max) <= _THETA_MAX_EPS:
        return limit.beta_at_theta_max

    def f(beta: float) -> float:
        return theta_from_beta(M1_val, beta, gamma_val) - theta

    if branch == "weak":
        lo, hi = mu + _BETA_EPS, limit.beta_at_theta_max
    else:
        lo, hi = limit.beta_at_theta_max, np.pi / 2.0 - _BETA_EPS

    f_lo, f_hi = f(lo), f(hi)
    if f_lo * f_hi > 0.0:
        # Should not occur given the unimodal structure and theta<=theta_max
        # check above, but fail loudly rather than returning a bad root.
        raise RuntimeError(
            f"Failed to bracket a sign change for branch={branch!r}, M1={M1_val}, "
            f"theta={theta}: f(lo)={f_lo}, f(hi)={f_hi}"
        )
    beta = brentq(f, lo, hi, xtol=1e-14, rtol=1e-14)
    return float(beta)


@dataclass
class ObliqueShockResult:
    """Single attached oblique-shock solution.

    Attributes
    ----------
    M1, theta, beta : inputs / solved shock angle (radians)
    branch : "weak" or "strong"
    Mn1, Mn2 : upstream/downstream Mach numbers normal to the shock
    M2 : full downstream Mach number
    p2_p1, rho2_rho1, T2_T1 : static ratios (from the normal-shock relations
        applied to Mn1)
    p02_p01 : stagnation-pressure recovery (< 1)

    Optional dimensional fields (populated only if an upstream thermodynamic
    state p1, T1 was supplied to `oblique_shock`; otherwise None):
    p1, T1, p2, rho2, T2, V1, V2, T0_1, T0_2.
    """

    M1: float
    theta: float
    beta: float
    branch: str
    Mn1: float
    Mn2: float
    M2: float
    p2_p1: float
    rho2_rho1: float
    T2_T1: float
    p02_p01: float

    p1: float | None = None
    T1: float | None = None
    p2: float | None = None
    rho2: float | None = None
    T2: float | None = None
    V1: float | None = None
    V2: float | None = None
    T0_1: float | None = None
    T0_2: float | None = None


def oblique_shock(
    M1: float,
    theta: float,
    gamma: float = DEFAULT_GAMMA,
    branch: str = "weak",
    p1: float | None = None,
    T1: float | None = None,
    R: float | None = None,
) -> ObliqueShockResult:
    """Solve a single attached oblique shock generated by a compression
    ramp of deflection angle `theta` (radians) in upstream flow M1.

    Procedure (see DESIGN.md for the full derivation):
      1. Solve the theta-beta-M relation for beta on the requested branch
         (`shock_angle`).
      2. Form the upstream normal Mach number Mn1 = M1*sin(beta).
      3. Apply the VERIFIED normal-shock relations (`normal_shock`) to Mn1
         to obtain Mn2, p2/p1, rho2/rho1, T2/T1, p0,2/p0,1 -- the tangential
         velocity component is unchanged across an ideal inviscid shock, so
         all of the normal-shock static/stagnation ratios carry over
         unchanged as the *oblique*-shock static/stagnation ratios.
      4. Recover the full downstream Mach number M2 = Mn2 / sin(beta-theta).

    If `p1` and `T1` (and optionally `R`) are supplied, dimensional
    downstream state (p2, rho2, T2, velocities, stagnation temperatures) is
    also populated on the result.
    """
    beta = shock_angle(M1, theta, gamma, branch)

    Mn1 = M1 * np.sin(beta)
    ns = normal_shock(Mn1, gamma)
    Mn2 = float(ns.M2)
    p2_p1 = float(ns.p2_p1)
    rho2_rho1 = float(ns.rho2_rho1)
    T2_T1 = float(ns.T2_T1)
    p02_p01 = float(ns.p02_p01)

    sin_beta_minus_theta = np.sin(beta - theta)
    M2 = Mn2 / sin_beta_minus_theta

    result = ObliqueShockResult(
        M1=float(M1),
        theta=float(theta),
        beta=float(beta),
        branch=branch,
        Mn1=float(Mn1),
        Mn2=Mn2,
        M2=float(M2),
        p2_p1=p2_p1,
        rho2_rho1=rho2_rho1,
        T2_T1=T2_T1,
        p02_p01=p02_p01,
    )

    if p1 is not None and T1 is not None:
        from scramjet_inlet.gas_dynamics import (
            DEFAULT_R,
            T0_over_T,
            velocity_from_mach,
        )

        R_val = DEFAULT_R if R is None else R
        T2 = T1 * T2_T1
        p2 = p1 * p2_p1
        rho1 = p1 / (R_val * T1)
        rho2 = rho1 * rho2_rho1
        V1 = float(velocity_from_mach(M1, T1, gamma, R_val))
        V2 = float(velocity_from_mach(M2, T2, gamma, R_val))
        T0_1 = T1 * float(T0_over_T(M1, gamma))
        T0_2 = T2 * float(T0_over_T(M2, gamma))

        result.p1 = float(p1)
        result.T1 = float(T1)
        result.p2 = float(p2)
        result.rho2 = float(rho2)
        result.T2 = float(T2)
        result.V1 = V1
        result.V2 = V2
        result.T0_1 = T0_1
        result.T0_2 = T0_2

    return result
